services:
  - type: web
    name: fractal
    env: python
    python_version: "3.12"  # Specify Python version here
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python your_app.py"